exp_name: sci_stage1
unet_config_path: ./unet_config.json
pretrained_unet_path: null
seed: 0
train_batch_size: 64
val_batch_size: 12
num_workers: 12
learning_rate: 5.0e-04
max_train_steps: 20000
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.001
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
scheduler_type: cosine
num_warmup_steps: 100
mixed_precision: fp16
gradient_accumulation_steps: 1
checkpointing_step_interv: 1000
validation_step_interv: 50
resume_from_checkpoint: null
output_dir: ./output