exp_name: sci_stage2
pretrained_unet_path: output/sci_stage1/pretrained
video_length: 8
seed: 0
train_batch_size: 16
val_batch_size: 3
num_workers: 12
learning_rate: 1.0e-05
max_train_steps: 5000
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.001
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
scheduler_type: constant_with_warmup
num_warmup_steps: 100
mixed_precision: fp16
gradient_accumulation_steps: 1
checkpointing_step_interv: 1000
validation_step_interv: 100
resume_from_checkpoint: null
output_dir: ./output